### PR TITLE
Add static analysis

### PR DESCRIPTION
**Pull request by szepeviktor**
Simply using the trait fires up static analysis 🚀

🔎 https://github.com/luminarix/enum-concern/actions/runs/12516141020/job/34914797809?pr=7

### CODE REVIEW

**Comment by xHeaven** [comment]
I like the workflow changes, but at this point perhaps we could break it up to separate workflow files? I'm thinking "phpstan.yml" and "dependency-analysis.yml" or something like that. I don't feel like the "phpstan" workflow should do this much stuff. What do you think?

Can you explain the `phpstan` configuration related change and the added enums, though? This PR would not check `tests/FunctionTest.php` at all and only yields an error for the two added enums because of the fact that they both only have *a single* `case` in them*. I'd also put them in the `tests/Enums` directory, but I'm really not sure what it's supposed to add to the tests as we already have enum implementations for the tests.

*this is fixed [here](https://github.com/luminarix/enum-concern/pull/7/commits/5949f7a6c5993b34ce234e618caf4ee4bd6aee25)

**Comment by szepeviktor** [comment]
> I don't feel like the "phpstan" workflow should do this much stuff. What do you think?

My workflows concentrate on a certain target, jobs on a certain type of check
workflow name = back-end thus PHP language
job name = static analysis
https://github.com/szepeviktor/byte-level-care/blob/master/.github/workflows/back-end.yml#L131

It is up to you!

> This PR would not check tests/FunctionTest.php at all

Those test files were included because nothing else used the trait.
Now there are 2 classes only to use the trait, so no need for Pest tests.

**Comment by szepeviktor** [comment]
It is merge time.

**Comment by xHeaven** [comment]
> My workflows concentrate on a certain target, jobs on a certain type of check workflow name = back-end thus PHP language job name = static analysis [szepeviktor/byte-level-care@`master`/.github/workflows/back-end.yml#L131](https://github.com/szepeviktor/byte-level-care/blob/master/.github/workflows/back-end.yml?rgh-link-date=2024-12-27T18%3A28%3A55Z#L131)
> 
> It is up to you!

We might just leave it as-is for now, I'll do a cleanup on the workflows later.

> Those test files were included because nothing else used the trait. Now there are 2 classes only to use the trait, so no need for Pest tests.

Can you check [my latest commit](https://github.com/luminarix/enum-concern/pull/7/commits/ab0e3558644ae8f76bdf5488d62eb61cdc3d3d7f)? What do you think about this? We already have enums that make use of the trait - they are specifically made for the tests, however, we can also use them to trigger the static analysis on the trait itself as well. Would you prefer creating separate, unused enums instead just to trigger the SA? If so, why?

**Comment by szepeviktor** [comment]
> we can also use them to trigger the static analysis on the trait itself as well.

I agree.

I didn't know about those enums.

**Pull request merged**
